---
aliases:
  # Forward the current folder when using wokflows
  #   persist-to-workspace & attach-workspace
  - &persist-work-dir
    root: .
    paths: .

  - &attach-work-dir
    at: ~/app/

  # Dependencies
  - &yarn
    name: Run Yarn
    command: |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

defaults: &defaults
  working_directory: ~/app
  environment:
    NODE_ENV: 'test'

version: 2

jobs:
  checkout:
    docker:
      - image: circleci/node:10.17.0
    steps:
      - checkout

      - run: *yarn

      - persist-to-workspace: *persist-work-dir

  release:
    <<: *defaults
    docker:
      - image: circleci/node:10.17.0

    steps:
      - attach-workspace: *attach-work-dir

      - run: yarn semantic-release

workflows:
  version: 2
  suite:
    jobs:
      - checkout
      - release:
          requires:
            - checkout
