---
aliases:
  # Forward the current folder when using wokflows
  #   persist-to-workspace & attach-workspace
  - &persist-work-dir
    root: .
    paths: .

  - &attach-work-dir
    at: ~/app/

  # Dependencies
  - &yarn
    name: Run Yarn
    command: |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:14.18.3-browsers
  environment:
    NODE_ENV: 'test'

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run: *yarn

      - persist-to-workspace: *persist-work-dir

  lint:
    <<: *defaults

    steps:
      - attach-workspace: *attach-work-dir

      - run: yarn lint

  test:
    <<: *defaults

    steps:
      - attach-workspace: *attach-work-dir

      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

      - run: yarn build

      - run:
          command: "npm run ci:start"
          background: true

      - run:
          command: "npm run test"

  release:
    <<: *defaults

    steps:
      - attach-workspace: *attach-work-dir

      - setup_remote_docker:
          version: 19.03.13

      - run: yarn semantic-release

      - run:
          name: Docker Build
          command: yarn docker:build
      - run:
          name: Docker publish
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            yarn docker:release

workflows:
  version: 2
  suite:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
