---
version: 2.1

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:16.13.1
  environment:
    NODE_ENV: 'test'

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run: yarn install --non-interactive --cache-folder ~/.cache/yarn

      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app/

      - run: yarn lint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app/

      - run: yarn build

      - run:
          command: "yarn ci:start"
          background: true

      - run:
          command: |
            sleep 10s && yarn test

  release:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/app/

      - setup_remote_docker:
          version: 19.03.13

      - run: yarn semantic-release

      - run:
          name: Docker Build
          command: yarn docker:build
      - run:
          name: Docker publish
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            yarn docker:release

workflows:
  version: 2
  suite:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
