---
aliases:
  # Forward the current folder when using wokflows
  #   persist-to-workspace & attach-workspace
  - &persist-work-dir
    root: .
    paths: .

  - &attach-work-dir
    at: ~/app/

  # Dependencies
  - &yarn
    name: Run Yarn
    command: |
      yarn install --non-interactive --cache-folder ~/.cache/yarn

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12.16.2
  environment:
    NODE_ENV: 'test'

version: 2

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run: *yarn

      - persist-to-workspace: *persist-work-dir

  lint:
    <<: *defaults

    steps:
      - attach-workspace: *attach-work-dir

      - run: yarn lint

  test:
    <<: *defaults

    steps:
      - attach-workspace: *attach-work-dir

      - run: yarn build

      - run:
          command: npm start
          background: true

      - run: "sleep 2"
      - run: "curl -sS http://localhost:3000/ready"
      - run: "curl -sS http://localhost:3000/render?url=http%3A%2F%2Flocalhost%3A3000%2Ftest-website%2Fbasic.html | grep 'A basic page'"
      - run: "curl -sS http://localhost:3000/render?url=http%3A%2F%2Flocalhost%3A3000%2Ftest-website%2Floads.html | grep 'Init'"

  release:
    <<: *defaults

    steps:
      - attach-workspace: *attach-work-dir

      - run: yarn semantic-release

workflows:
  version: 2
  suite:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - release:
          requires:
            - lint
            - test
