name: Renderscript

on:
  push:
    branches:
      - "master"
      - "renovate/**"
  pull_request:

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "true"
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install

      - name: Run Linter
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    name: Tests
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install

      - name: Build
        run: yarn build

      - name: Background process
        run: |
          yarn ci:start &

      - name: Run test
        run: yarn test

