name: Release Version
on:
  workflow_dispatch:
    inputs:
      dry_run:
        required: true
        type: boolean
        default: true
        description: 'DryRun?'

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIT_AUTHOR_NAME: ${{ secrets.GH_USER_NAME }}
      GIT_AUTHOR_EMAIL: ${{ secrets.GH_USER_EMAIL }}
      GIT_COMMITTER_NAME: ${{ secrets.GH_USER_NAME }}
      GIT_COMMITTER_EMAIL: ${{ secrets.GH_USER_EMAIL }}

    steps:
      - uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials.
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Release (--dry-run)
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true')
        run: |
          yarn install
          yarn semantic-release --dry-run

      - name: Release
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run != 'true')
        run: |
          yarn install
          yarn semantic-release
