name: Release Docker
on:
  workflow_run:
    workflows: ["Release Version"]
    branches: [master]
    types:
      - completed

  workflow_dispatch:
    inputs:
      is_release:
        required: true
        type: boolean
        description: "Is this a release image?"

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Dockers
    if: (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch')

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc

      - name: Setting env var
        id: env_var
        shell: bash
        run: |
          echo "::set-output name=RENDERSCRIPT_VERSION::$(node -e 'console.log(require("./package.json").version)')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker QEMU for arm64 docker builds
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Build Image
        uses: docker/build-push-action@v2.7.0
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64 # buildx does not support multi-arch load
          push: false
          load: true
          tags: |
            algolia/renderscript:latest
            algolia/renderscript:${{ steps.env_var.outputs.RENDERSCRIPT_VERSION }}
            algolia/renderscript:${{ env.COMMIT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.env_var.outputs.RENDERSCRIPT_VERSION }}

      - name: Test Image
        run: ./scripts/test_image.sh ${{ env.COMMIT_SHA }}

      # Cache should be reused from prev execution
      - name: Push
        if: (github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_release == 'true')
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            algolia/renderscript:latest
            algolia/renderscript:${{ steps.env_var.outputs.RENDERSCRIPT_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.env_var.outputs.RENDERSCRIPT_VERSION }}
